README: Fix punctuation.
cloud-hypervisor/rust-hypervisor-firmware pull request #137
Opened 2021-07-07 21:02 UTC by yyu

2021-07-16 11:02 UTC, retrage requested changes
Each commit must have a "signed-off by" signature as the DCO bot indicates.

2021-07-16 22:06 UTC, yyu commented on README.md
> +https://github.com/cloud-hypervisor/rust-hypervisor-firmware/security/advisories/new.
done.

2021-07-18 08:56 UTC, rbradford commented
This should also be squashed into one commit.

2021-07-20 06:21 UTC, yyu commented
> This should also be squashed into one commit.

done

2021-07-22 05:08 UTC, retrage requested changes
Please add `Signed-off-by` to the commit.
See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

2021-07-23 05:03 UTC, retrage approved these changes
Thanks!

2021-09-24 08:21 UTC, closed without merging